FROM almalinux:9
ENV course="Devops with AWS"\
    trainer="siva kumar"\
    duration="120HRS"
#Here username is key, some_user is default value.
ARG USERNAME=Balaguru
RUN echo "Hello User: ${USERNAME}"
CMD [ "sleep", "200" ]